name: airflow

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  files-changed:
    name: detect file change
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      airflow: ${{ steps.changes.outputs.airflow }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@main
      - name: Check for backend file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yaml

  build:
    if: needs.files-changed.outputs.airflow == 'true'
    needs: files-changed
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: shepherd9664/airflow
          tags: |
            type=raw,value=v2.8-python3.11-{{date 'YYYY.MM.DD-HHmm' tz='Asia/Seoul'}}
            v2.8-python3.11-latest
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./docker/airflow
          file: docker/airflow/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
