name: apache-spark-override-3-5

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  files-changed:
    name: detect file change
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      apache_spark_override: ${{ steps.changes.outputs.apache_spark_override }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@main

      - name: Check for backend file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yaml

  build:
    if: needs.files-changed.outputs.apache_spark_override == 'true'
    needs: files-changed
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: shepherd9664/spark
          tags: |
            type=raw,value=3.5-{{date 'YYYY.MM.DD-HHmm' tz='Asia/Seoul'}}
            type=raw,value=3.5.0-{{date 'YYYY.MM.DD-HHmm' tz='Asia/Seoul'}}
            3.5-latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./containers/apache_spark_override
          file: containers/apache_spark_override/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SPARK_VERSION=3.5.0
            HADOOP_VERSION=3.3.4
            SCALA_VERSION=2.12
            HIVE_VERSION=2.3.9
            ICEBERG_VERSION=1.4.3
