name: awscli

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/awscli.yml'
      - 'containers/awscli/**'

  pull_request:
    branches: [ "main" ]

jobs:
  files-changed:
    name: detect file change
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      awscli: ${{ steps.changes.outputs.awscli }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@main
      - name: Check for backend file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yaml

  build:
    if: needs.files-changed.outputs.awscli == 'true'
    needs: files-changed
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: shepherd9664/awscli
          tags: |
            type=raw,value={{date 'YYYY.MM.DD-HHmm' tz='Asia/Seoul'}}
            latest
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./containers/awscli
          file: containers/awscli/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
