name: awscli

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/awscli.yml'
      - 'containers/awscli/**'

  pull_request:
    branches: [ "main" ]
    paths:
      - 'containers/awscli/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: shepherd9664/awscli
          tags: |
            type=raw,value=2.15.34-postgres14-{{date 'YYYY.MM.DD-HHmm' tz='Asia/Seoul'}}
            type=raw,value=latest
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./containers/awscli
          file: containers/awscli/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            AWSCLI_VERSION=2.15.34
            POSTGRES_VERSION=14
